### ISSUE TITLE
pip install . fails 

### ISSUE THREAD

**Issue by goncayilmaz** [liu115/renderpy#1]
Hello,

I am following your instructions on linux to build the package. Unfortunately, I am getting the following errors:

CMake Error at CMakeLists.txt:22 (find_package):
        By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "OpenCV", but
        CMake did not find one.
      
        Could not find a package configuration file provided by "OpenCV" with any
        of the following names:
      
          OpenCVConfig.cmake
          opencv-config.cmake
      
        Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
        "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
        provides a separate development package or SDK, be sure it has been
        installed.
      
      
      -- Configuring incomplete, errors occurred!
      See also "/cluster/project/cvg/students/gyilmaz/scannetpp/renderpy/build/temp.linux-x86_64-3.10/renderpy/CMakeFiles/CMakeOutput.log".
      See also "/cluster/project/cvg/students/gyilmaz/scannetpp/renderpy/build/temp.linux-x86_64-3.10/renderpy/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/cluster/project/cvg/students/gyilmaz/scannetpp/renderpy/setup.py", line 128, in <module>
          setup(
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/cluster/project/cvg/students/gyilmaz/scannetpp/renderpy/setup.py", line 118, in build_extension
          subprocess.run(
        File "/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '/cluster/project/cvg/students/gyilmaz/scannetpp/renderpy', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/cluster/project/cvg/students/gyilmaz/scannetpp/renderpy/build/lib.linux-x86_64-3.10/', '-DPYTHON_EXECUTABLE=/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DEXAMPLE_VERSION_INFO=0.0.1']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for renderpy

**Comment by gbliao** [comment]
@goncayilmaz Hi, may I ask how you solved it?

**Comment by ZheningHuang** [comment]
Hi, did you solve this problem. we are facing same situation here.

**Comment by liu115** [comment]
If you're using ubuntu and has sudo, you can install opencv and it should work
```
apt-get install libopencv-dev
```
If you have locally compiled the opencv library, you can specifiy `OpenCV_DIR` so that cmake could find it:

```
# Linux
export OpenCV_DIR=<path_of_opencv/build>

# Windows power shell
$env:OpenCV_DIR = "C:\path_of_opencv\build"
```

**Comment by sriharikg2003** [comment]
> If you're using ubuntu and has sudo, you can install opencv and it should work
> 
> ```
> apt-get install libopencv-dev
> ```
> 
> If you have locally compiled the opencv library, you can specifiy `OpenCV_DIR` so that cmake could find it:
> 
> ```
> # Linux
> export OpenCV_DIR=<path_of_opencv/build>
> 
> # Windows power shell
> $env:OpenCV_DIR = "C:\path_of_opencv\build"
> ```

I had similar issues :  

apt-get install libopencv-dev

Solved by : 

sudo apt-get install libopencv-dev
sudo apt-get install libgl1-mesa-dev
sudo apt-get install libxrandr-dev
