### ISSUE TITLE
EGL Error when caling the render function

### ISSUE THREAD

**Issue by Bensong0506** [liu115/renderpy#2]
File "/shared/scannetpp/common/render.py", line 47, in main
    render_engine = renderpy.Render()
RuntimeError: EGL error at eglInitializewith error code: 12296

Hi I managed to install and build the renderpy in the conda environment, but I got this error and I had no idea how to solve it.

**Comment by burui11087** [comment]
+1

**Comment by liu115** [comment]
Hi! I didn't have this issues before. Could you share a bit about your environment? like operating system, version, nvidia driver version etc.

Did you have the opengl package properly installed? is it installed in the conda env or in the system using apt install?

Some people also have this error when EGL init but fixed by upgrading the nvidia driver
https://stackoverflow.com/questions/61566660/error-in-eglinitialize-using-pyopengl-err-12296

**Comment by Sunwenxin1** [comment]
> Hi! I didn't have this issues before. Could you share a bit about your environment? like operating system, version, nvidia driver version etc.
> 
> Did you have the opengl package properly installed? is it installed in the conda env or in the system using apt install? (like libgl1-mesa-dev libglu1-mesa-dev)
> 
> Some people also have this error when EGL init but fixed by upgrading the nvidia driver
> 
> * https://stackoverflow.com/questions/61566660/error-in-eglinitialize-using-pyopengl-err-12296
> * [OpenGL.error.GLError: GLError( 	err = 12289, mkocabas/VIBE#47](https://github.com/mkocabas/VIBE/issues/47)

hello, sir. I met the OpenGL.error.GLError: err=12289. some information about my environment are as follows.
![Snipaste_2024-03-18_10-50-09](https://github.com/liu115/renderpy/assets/102956809/76da5c4d-27f9-49a4-ac0c-48a84fc3b7e5)

**Comment by XiangyuSu611** [comment]
I have the same issue.

![image](https://github.com/liu115/renderpy/assets/34934357/8b806a8f-001b-4854-a62c-58ec79e3bd87)

**Comment by Sunwenxin1** [comment]
> I have the same issue.
> 
> ![image](https://private-user-images.githubusercontent.com/34934357/316471547-8b806a8f-001b-4854-a62c-58ec79e3bd87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjM5NDksIm5iZiI6MTcxMTM2MzY0OSwicGF0aCI6Ii8zNDkzNDM1Ny8zMTY0NzE1NDctOGI4MDZhOGYtMDAxYi00ODU0LWE2MmMtNThlYzc5ZTNiZDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEwNDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYTc0OTg2YWUzMGVjZDhmOTJmMWFkOTBmOWVjZWI0YTFhZDdhNzVlZDFhZjUyZTAyNWQzZjk2YzI3ZWQxOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5QeLfPf3DBsMtDhy_54aEexpKVJvx-KpRU-zavJzv7M)

i met this problem when i tried to run the VIBE project. my error is 12289 while yours is 12296. maybe the pyrender or the EGL is the reason. when i tried VIBE in the COLAB, the problem disappeared.

**Comment by liu115** [comment]
Thanks for reporting. I will try different machines and environments and see if I can reproduce the issue but it might take a while.

At the meantime, a quick solution will be using other tools to do the rendering. I assume the main usage here is to render depth for ScanNet++ images. An alternative we had tried is to use pytorch3d MeshRasterizer.
Reference that render semantic labels into 2D: https://github.com/scannetpp/scannetpp/blob/main/semantic/prep/rasterize_semantics_2d.py
you should be able to read the z-buffer the get the depth map.

**Comment by zhanghaoyu816** [comment]
Is there any better solution for this error? I have also encountered this error with Ubuntu22.04
![image](https://github.com/liu115/renderpy/assets/60644792/9ddf3dad-ae0e-48ce-a06e-07aa075ffbcb)
![image](https://github.com/liu115/renderpy/assets/60644792/f7058b4e-d034-4b14-92cf-b743531b6f5c)
My device infomation:
![image](https://github.com/liu115/renderpy/assets/60644792/e92ebb8d-9f99-4523-a169-95d6810988e5)
![image](https://github.com/liu115/renderpy/assets/60644792/5fbf6f49-2e9b-4f4f-96dd-08c144aa39ef)
![image](https://github.com/liu115/renderpy/assets/60644792/5fd5c7d0-bbf4-4385-a83d-1a8835c007ad)

**Comment by YHChen0511** [comment]
I met this problem too. Are there any possible solutions?

**Comment by junyuan-fang** [comment]
I also have EGL error：
![image](https://github.com/user-attachments/assets/4d0b2923-495a-4e4f-aebe-0928ea82eef2)

['Render', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__']
Init EGL
Detected 4 devices
Using device 0
Using EGL version 1.5
OpenGL version: 4.6.0 NVIDIA 550.107.02
EGL version: 1.5
Bus error (core dumped)

**Comment by miaolin968** [comment]
@junyuan-fang Have you fixed this problem?

**Comment by junyuan-fang** [comment]
@miaolin968 Nope. Have you?

**Comment by miaolin968** [comment]
@junyuan-fang Nope.
And my problem is:
![image](https://github.com/user-attachments/assets/a026880b-3140-4b50-b19d-776f20356ce0)
"Detected 0 devices" means EGL can't detecte my GPU

**Comment by tsj-001** [comment]
I also meet the similar problem, is there any solution?
<img width="325" alt="Snipaste_2024-10-27_20-42-44" src="https://github.com/user-attachments/assets/a9fb2831-d8b6-42dd-a2a4-f3a095fdf3dc">

**Comment by mokrueger** [comment]
@junyuan-fang
can you check if your issue is related to https://github.com/liu115/renderpy/issues/4 ?

**Comment by winka9587** [comment]
A potential solution, I carefully checked the content in the provided link. 

I was processing the Scannet++ dataset.

~~~bash
$python -m common.render common/configs/render.yml
scene:   0%|                                                                                                                                                                                                              | 0/2 [00:00<?, ?it/s]Init EGL
Detected 0 devices
scene:   0%|                                                                                                                                                                                                              | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/scanntpp/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/scanntpp/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/SplaTAM_Nik-V9_scannetpp/common/render.py", line 91, in <module>
    main(args)
  File "/data/SplaTAM_Nik-V9_scannetpp/common/render.py", line 49, in main
    render_engine = renderpy.Render()
RuntimeError: Failed to initialize EGL
~~~

In my case, the issue was caused by adding the **--no-opengl-files** parameter during the GPU driver installation on the server. Reinstalling the GPU driver (using the same version as before) without any additional parameters resolved the problem.

In previous projects involving open3 visualization, I had to include additional parameters during gpu driver installation to ensure it worked correctly:

~~~
sudo ./NVIDIA-Linux-x86_64-{version}.run --no-opengl-files -no-x-check -no-nouveau-check
~~~

Below is the command I used to reinstall the GPU driver:

~~~
sudo ./NVIDIA-Linux-x86_64-{version}.run
~~~

now it works well

~~~bash
$python -m common.render common/configs/render.yml
scene:   0%|                                                                                                                                                                                                              | 0/2 [00:00<?, ?it/s]Init EGL
Detected 8 devices
Using device 0
Using EGL version 1.5
~~~


> Hi! I didn't have this issues before. Could you share a bit about your environment? like operating system, version, nvidia driver version etc.
> 
> Did you have the opengl package properly installed? is it installed in the conda env or in the system using apt install? (like libgl1-mesa-dev libglu1-mesa-dev)
> 
> Some people also have this error when EGL init but fixed by upgrading the nvidia driver
> 
> * https://stackoverflow.com/questions/61566660/error-in-eglinitialize-using-pyopengl-err-12296
> * [OpenGL.error.GLError: GLError( 	err = 12289, mkocabas/VIBE#47](https://github.com/mkocabas/VIBE/issues/47)

**Comment by fangzhou2000** [comment]
A possible solution:
For me, it works.

https://blog.csdn.net/wj1205time/article/details/143887974
